name: Build test
on:
  push:
    tags:
  pull_request:
    branches:
      - master
env:
  MASTER_BRANCH: refs/heads/master
jobs:
  native-build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python-version: [3.6]
    steps:
    - name: Git config
      run: git config --global core.symlinks true
      if: startsWith(matrix.platform, 'windows-')
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages(Ubuntu)
      if: startsWith(matrix.platform, 'ubuntu-')
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        sudo apt-get update && sudo apt-get install -y \
            cmake \
            curl \
            libassimp-dev \
            libcurl4-openssl-dev \
            libeigen3-dev \
            libfreetype6-dev \
            libglu1-mesa-dev \
            libgl1-mesa-dev \
            liblz4-dev \
            libtinyxml-dev \
            libtinyxml2-dev \
            libxaw7-dev \
            libxrandr-dev \
            libx11-dev \
            libyaml-dev \
            qtbase5-dev
    - name: Install packages(MacOS)
      if: startsWith(matrix.platform, 'macos-')
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        python3-config --ldflags
        python3-config --includes
        ls -al $(dirname $(which python3-config))/../lib
        sudo xcode-select -s '/Applications/Xcode_11.2.1.app/Contents/Developer'
        brew install \
            assimp \
            cmake \
            curl \
            eigen \
            freetype \
            libyaml \
            qt \
            tinyxml \
            tinyxml2
        echo "Qt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5" >> $GITHUB_ENV
    - name: Install rospy-build
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install ros2py_builder/
    - name: Cache dist
      uses: actions/cache@v2
      with:
        path: |
          dist
        key: ${{ github.ref }}-${{ matrix.platform }}-${{ matrix.python-version }}
    - name: Build packages
      run: |
        env
        ros2py-build
      shell: bash

