name: Build test
on:
  push:
    tags:
  pull_request:
    branches:
      - master
env:
  MASTER_BRANCH: refs/heads/master
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel pipenv
        pipenv install --dev
    - name: Test
      run: |
        pipenv run black --version
        pipenv run python --version
        pipenv run black --diff --check ros2py_init
        pipenv run black --diff --check ros2py_builder
        pipenv run isort --diff --check-only ros2py_init
        pipenv run isort --diff --check-only ros2py_builder
        pipenv run mypy ros2py_init
        pipenv run mypy ros2py_builder
  source-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install rospy-build
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install ros2py_builder/
    - name: Build source packages
      run: |
        ros2py-build --source
    - uses: actions/upload-artifact@v2
      with:
        name: source
        path: dist
  native-build:
    needs: source-build
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - name: Git config
      run: git config --global core.symlinks true
      if: startsWith(matrix.platform, 'windows-')
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages(Ubuntu)
      if: startsWith(matrix.platform, 'ubuntu-')
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        sudo apt-get update && sudo apt-get install -y \
            cmake \
            curl \
            libassimp-dev \
            libcurl4-openssl-dev \
            libeigen3-dev \
            libfreetype6-dev \
            libglu1-mesa-dev \
            libgl1-mesa-dev \
            liblz4-dev \
            libtinyxml-dev \
            libtinyxml2-dev \
            libxaw7-dev \
            libxrandr-dev \
            libx11-dev \
            libyaml-dev \
            qtbase5-dev
    - name: Install packages(MacOS)
      if: startsWith(matrix.platform, 'macos-')
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        sudo xcode-select -s '/Applications/Xcode_11.2.1.app/Contents/Developer'
        brew install \
            assimp \
            cmake \
            curl \
            eigen \
            freetype \
            libyaml \
            qt \
            tinyxml \
            tinyxml2
        echo "Qt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5" >> $GITHUB_ENV
    - name: Install rospy-build
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install ros2py_builder/
    - name: Download source packages
      uses: actions/download-artifact@v2
      with:
        name: source
        path: dist
    - name: Cache binary packages
      uses: actions/cache@v2
      with:
        path: |
          dist/*.whl
        key: ${{ github.ref }}-${{ matrix.platform }}-${{ matrix.python-version }}
    - name: Build binary packages
      run: |
        ros2py-build
      shell: bash
    - name: Upload binary packages
      uses: actions/upload-artifact@v2
      with:
        name: binary-${{ matrix.platform }}-${{ matrix.python-version }}
        path: dist/*.whl
